### ISSUE TITLE
Handle non-json response to prevent app crash

### ISSUE THREAD

**Issue by aivus** [aivus/com.gree#27]
A crash occurred for your app (version 0.1.3) at Sep 26, 2019 10:45 PM (UTC).

Homey software version: 2.5.2

Crash report:
```
    undefined:1
<?xml version="1.0" encoding="UTF-8"?>
^

SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Client._handleResponse (/node_modules/gree-hvac-client/lib/client.js:268:30)
    at Socket._socket.on.message (/node_modules/gree-hvac-client/lib/client.js:110:52)
    at emitTwo (events.js:126:13)
    at Socket.emit (events.js:214:7)
    at UDP.onMessage [as onmessage] (dgram.js:659:8)
```

**Comment by aivus** [comment]
Should be fixed in https://github.com/inwaar/gree-hvac-client/pull/6
